/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.1/userguide/multi_project_builds.html
 */

pluginManagement {
    repositories {
        mavenLocal()
        maven(url = "https://jitpack.io")
        mavenCentral()
    }

    resolutionStrategy {
        eachPlugin {
            if (requested.id.toString() == "pl.allegro.tech.build.axion-release") {
                useModule("com.github.allegro:axion-release-plugin:${requested.version}")
            }
        }
    }
}

rootProject.name = "axion-release-example"
include("app")
